# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Fecha/Hora')),
                ('up', models.BooleanField(default=False, verbose_name='¿Sitio activo?')),
                ('last_event', models.CharField(choices=[('0', 'No hay eventos anteriores'), ('1', 'Activo'), ('2', 'Inactivo')], default='0', max_length=1, verbose_name='Estado anterior')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('up', models.BooleanField(default=False, verbose_name='¿Sitio activo?')),
                ('status_code', models.CharField(default='0', max_length=4, verbose_name='Status Code')),
                ('elapsed_time', models.FloatField(help_text='Tiempo transcurrido desde la petición original en milisegundos', null=True, verbose_name='Tiempo transcurrido')),
                ('mensaje', models.CharField(blank=True, max_length=120, verbose_name='Log')),
            ],
            options={
                'verbose_name': 'Estado (ping)',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(help_text='No olvide incluir el prefijo http o https según corresponda', max_length=120, unique=True, verbose_name='URL')),
                ('timeout', models.IntegerField(default=1000, help_text='Tiempo de espera máximo en milisegundos.', verbose_name='Timeout')),
            ],
            options={
                'verbose_name': 'Sitio web',
                'verbose_name_plural': 'Sitios web',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertas_activas', models.CharField(choices=[('on', 'Siempre'), ('off', 'Apagadas'), ('maybe', 'Personalizadas')], default='on', help_text='Configuración global', max_length=10, verbose_name='Alertas Activas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerta_email', models.BooleanField(default=True, verbose_name='Alerta x Email')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_website', to='uptime.Site')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ping',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='uptime.Site'),
        ),
        migrations.AddField(
            model_name='evento',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='uptime.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariowebsite',
            unique_together=set([('usuario', 'site')]),
        ),
    ]
